### ISSUE TITLE
Please mention the details of working Android version

### ISSUE THREAD

**Issue by sqzhang-jeremy** [MobileLLM/AutoDroid#11]

**Comment by leosol** [comment]
It workd for me with an SM-A910F Android 8: 
[ro.build.fingerprint]: [samsung/a9xproltedx/a9xproltesea:8.0.0/R16NW/A910FUBU1CRJ1:user/release-keys]

**Comment by sqzhang-jeremy** [comment]
> It workd for me with an SM-A910F Android 8: [ro.build.fingerprint]: [samsung/a9xproltedx/a9xproltesea:8.0.0/R16NW/A910FUBU1CRJ1:user/release-keys]

My version is Samsung Galaxy A04s Android 13: [ro.build.fingerprint]: 
[samsung/a04snnxx/a04s:13/TP1A.220624.014/A047FXXS5CWJ1:user/release-keys]

Thank you. So sad to hear that this project doesn't support advanced Android.

**Comment by wenh18** [comment]
We run it on Android 11 with API 30, because droidbot does not support Android version above 12.0, we are sorry for the inconvenience.

**Comment by sqzhang-jeremy** [comment]
> We run it on Android 11 with API 30, because droidbot does not support Android version above 12.0, we are sorry for the inconvenience.

Fine. Thank u

**Comment by hangyin62** [comment]
It can support if you update minicap.so files and fix those adb result parsing.
