### ISSUE TITLE
How to use a local llm or open source model

### ISSUE THREAD

**Issue by alexsiu398** [MobileLLM/AutoDroid#13]
I saw the research paper mentioned "The local LLM Vicuna-7B [6] is deployed on the smartphone
based on Machine Learning Compilation for LLM (MLCLLM)". How to setup the local llm and run the ./scripts with local llm?

**Comment by wenh18** [comment]
We deployed Vicuna-7B on smartphone only to evaluate its per-step inference latency, and did not run the whole pipline of AutoDroid on it, as we believe this requires only engineering efforts. You could refer to our artifacts repo https://github.com/autodroid-sys/artifacts/tree/main/Fastchat for fine-tuning Vicuna-7B.

**Comment by alexsiu398** [comment]
the local llm can be hosted on computer instead of the smartphone.
