### ISSUE TITLE
No module named 'memory.memory_builder'

### ISSUE THREAD

**Issue by Inception41** [MobileLLM/AutoDroid#2]
hi, i just run "droidbot -h" or  any .sh in ./scripts folder will get the error "from memory.memory_builder import Memory
ModuleNotFoundError: No module named 'memory.memory_builder'" ,but it is ok to run  "droidbot -h" when i follow the step in https://github.com/honeynet/droidbot/ .  It means i cant run the code in atuodroid, how can i fix this problem? thank you

**Comment by wenh18** [comment]
Sorry, we have fixed the bug.
