### ISSUE TITLE
开源代码问题请教

### ISSUE THREAD

**Issue by xutianchen123** [MobileLLM/AutoDroid#4]
作者您好，拜读了您的文章，受益匪浅。关于代码开源方面我有一点问题想要请教。请问文章中提及的离线阶段中，AutoDroid结合UTG生成模拟任务这一块体现在代码的哪一个部分，望解答，谢谢！

**Comment by wenh18** [comment]
感谢您的关注！由于一些问题我们目前还没有公开这部分代码，不过在这里有模拟任务的生成结果[AutoDroid](https://github.com/MobileLLM/AutoDroid/tree/newbranch)/[memory](https://github.com/MobileLLM/AutoDroid/tree/newbranch/memory)
/element_description.json，我们也会在之后的工作中尝试更好的生成方法，敬请关注！
